fix: no more jest-junit, use built-in github actions reporter

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -160,18 +160,11 @@ jobs:
           npm ci --offline
 
       - name: Run tests
-        env:
-          JEST_JUNIT_OUTPUT_DIR: reports/
-          JEST_JUNIT_OUTPUT_NAME: unit-tests.xml
+        shell: bash
+        id: tests
+        continue-on-error: true # continue so that we still run analysis
         run: |
-          npm run test:ci -- --coverage --testLocationInResults --reporters=default --reporters=jest-junit
-        continue-on-error: true
-
-      - name: Upload unit-test results
-        uses: enricomi/publish-unit-test-result-action@283dea176069279a9076e77b548668a8e4f0c31b # v2.9.0
-        with:
-          check_name: Unit-test results
-          files: reports/unit-tests.xml
+          npm run test:ci
 
       - name: Setup Code Climate test-reporter
         shell: bash
@@ -187,6 +180,13 @@ jobs:
         run: |
           ./cc-test-reporter format-coverage coverage/lcov.info --input-type lcov --output reports/codeclimate.json
           ./cc-test-reporter upload-coverage --input reports/codeclimate.json
+
+      - name: Fail if tests failed
+        shell: bash
+        if: steps.tests.outcome != 'success'
+        run: |
+          echo "Tests failed"
+          exit 1
 
   npm-dependencies:
     name: Validate dependencies
